# Generated by Django 2.0.4 on 2018-05-07 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('address', models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion')),
                ('location', models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion')),
                ('rating', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
                ('schedule', models.CharField(default='--', max_length=150, verbose_name='Horarios')),
            ],
            options={
                'verbose_name': 'Agencia de turismo',
                'verbose_name_plural': 'Agencias de turismo',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='AgencyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Servicio de Agencia',
                'verbose_name_plural': 'Servicios de Agencias',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('file', models.FileField(null=True, upload_to='documents/%Y/%m/%d', verbose_name='Archivo pdf')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['file'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('location', models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion')),
                ('event_date', models.DateField(verbose_name='Fecha de Evento')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciones',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Lodgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('address', models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion')),
                ('location', models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion')),
                ('rating', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
            ],
            options={
                'verbose_name': 'Hospedaje',
                'verbose_name_plural': 'Hospedajes',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='LodgmentRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=5.1, max_digits=5, verbose_name='Precio')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('lodgment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Lodgment', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Cuarto de Hospedaje',
                'verbose_name_plural': 'Cuartos de Hospedajes',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='LodgmentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('lodgment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Lodgment', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio de Hospedaje',
                'verbose_name_plural': 'Servicios de Hospedajes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LodgmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Tipo de Hospedaje',
                'verbose_name_plural': 'Tipos de Hospedajes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Objetive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('address', models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion')),
                ('location', models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('rating', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=5.1, max_digits=5, verbose_name='Precio')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Menu de Restaurante',
                'verbose_name_plural': 'Menus de Restaurantes',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Servicio de Restaurante',
                'verbose_name_plural': 'Servicios de Restaurantes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='NA', max_length=150, verbose_name='Dia')),
                ('description', models.CharField(default='NA', max_length=150, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Horario de Atencion',
                'verbose_name_plural': 'Horarios de Atencion',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='TourismSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('location', models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion')),
                ('rating', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('address', models.CharField(default='sn', max_length=150, verbose_name='Direccion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
                ('schedule', models.CharField(default='--', max_length=150, verbose_name='Horarios')),
            ],
            options={
                'verbose_name': 'Sitio turistico',
                'verbose_name_plural': 'Sitios turisticos',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('address', models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion')),
                ('location', models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion')),
                ('rating', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
                ('schedule', models.ManyToManyField(to='tour.Schedule', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='TransportDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Transport', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Destino de Transporte',
                'verbose_name_plural': 'Destinos de Transportes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Item de servicio')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Servicio de Transporte',
                'verbose_name_plural': 'Servicios  de Transportes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TransportTypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Servicio')),
                ('price', models.DecimalField(decimal_places=2, default=5.1, max_digits=5, verbose_name='Precio')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TransportDestination', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio de Transporte',
                'verbose_name_plural': 'Tipos de Servicios de Transportes',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='transportservice',
            name='type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TransportTypeService', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(to='tour.RestaurantMenu', verbose_name='Menu'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='schedule',
            field=models.ManyToManyField(to='tour.Schedule', verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service',
            field=models.ManyToManyField(to='tour.RestaurantService', verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='lodgment',
            name='schedule',
            field=models.ManyToManyField(to='tour.Schedule', verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='lodgment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.LodgmentType', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='agency',
            name='service',
            field=models.ManyToManyField(to='tour.AgencyService', verbose_name='Horario'),
        ),
    ]
