# Generated by Django 2.0.3 on 2018-04-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('description', models.TextField()),
                ('location', models.URLField()),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lodgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('description', models.TextField()),
                ('location', models.URLField()),
                ('rating', models.CharField(choices=[(1, '✭'), (2, '✭✭'), (3, '✭✭✭'), (4, '✭✭✭✭'), (5, '✭✭✭✭✭')], default=1, max_length=1)),
                ('phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Lodgmet_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('description', models.TextField()),
                ('location', models.URLField()),
                ('rating', models.CharField(choices=[(1, '✭'), (2, '✭✭'), (3, '✭✭✭'), (4, '✭✭✭✭'), (5, '✭✭✭✭✭')], default=1, max_length=1)),
                ('phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tourim_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('description', models.TextField()),
                ('location', models.URLField()),
                ('phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tourism_agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('description', models.TextField()),
                ('location', models.URLField()),
                ('phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('description', models.TextField()),
                ('location', models.URLField()),
                ('rating', models.CharField(choices=[(1, '✭'), (2, '✭✭'), (3, '✭✭✭'), (4, '✭✭✭✭'), (5, '✭✭✭✭✭')], default=1, max_length=1)),
                ('phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='lodgment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Lodgmet_type'),
        ),
    ]
