# Generated by Django 2.0.4 on 2018-06-20 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('address', models.CharField(default='S/N', max_length=150, verbose_name='Direccion')),
                ('score', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitud')),
                ('lng', models.CharField(max_length=50, verbose_name='Longitud')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Agencia de turismo',
                'verbose_name_plural': 'Agencias de turismo',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='AgencySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, verbose_name='Dia')),
                ('schedule', models.CharField(default='8:00 - 22:00', max_length=50, verbose_name='Horario')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Agency', verbose_name='Agencia')),
            ],
            options={
                'verbose_name': 'Horario de Atencion',
                'verbose_name_plural': 'Horarios de Atencion',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='AgencyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('duration', models.CharField(default='S/N', max_length=150, verbose_name='Duracion')),
                ('departures', models.CharField(default='S/N', max_length=150, verbose_name='Dias de expedicion')),
                ('schedule', models.CharField(default='S/N', max_length=150, verbose_name='Horas de Expedicion')),
                ('place_start', models.CharField(default='S/N', max_length=150, verbose_name='Lugar de Inicio')),
                ('places_to_known', models.CharField(default='S/N', max_length=500, verbose_name='Lugares a conocer')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Agency', verbose_name='Agencia')),
            ],
            options={
                'verbose_name': 'Paquete de Agencia',
                'verbose_name_plural': 'Paquetes de Agencias',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('file', models.FileField(null=True, upload_to='documents/%Y/%m/%d', verbose_name='Archivo pdf')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['file'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('file', models.FileField(null='true', upload_to='media/', verbose_name='Imagen o Video')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitud')),
                ('lng', models.CharField(max_length=50, verbose_name='Longitud')),
                ('event_date', models.DateField(verbose_name='Fecha de Evento')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciones',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('address', models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitud')),
                ('lng', models.CharField(max_length=50, verbose_name='Longitud')),
                ('score', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
            ],
            options={
                'verbose_name': 'Hospedaje',
                'verbose_name_plural': 'Hospedajes',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='LodgingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=5.1, max_digits=5, verbose_name='Precio')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Lodging', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Cuarto de Hospedaje',
                'verbose_name_plural': 'Cuartos de Hospedajes',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='LodgingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, verbose_name='Dia')),
                ('schedule', models.CharField(default='7:00 - 23:00', max_length=50, verbose_name='Horario')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Lodging', verbose_name='Hospedaje')),
            ],
            options={
                'verbose_name': 'Horario de Atencion de Hospedaje',
                'verbose_name_plural': 'Horarios de Atencion de Hospedajes',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='LodgingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Servicio de Hospedaje',
                'verbose_name_plural': 'Servicios de Hospedajes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LodgingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Tipo de Hospedaje',
                'verbose_name_plural': 'Tipos de Hospedajes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('address', models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitud')),
                ('lng', models.CharField(max_length=50, verbose_name='Longitud')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('score', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=5.1, max_digits=5, verbose_name='Precio')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Menu de Restaurante',
                'verbose_name_plural': 'Menus de Restaurantes',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, verbose_name='Dia')),
                ('schedule', models.CharField(default='NA', max_length=50, verbose_name='Horario')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Horario de Atencion de Restaurant',
                'verbose_name_plural': 'Horarios de Atencion de Restaurantes',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Servicio de Restaurante',
                'verbose_name_plural': 'Servicios de Restaurantes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TourismRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('lat_origin', models.CharField(max_length=50, verbose_name='Latitud de Origen')),
                ('lng_origin', models.CharField(max_length=50, verbose_name='Longitud de Origen')),
                ('lat_destination', models.CharField(max_length=50, verbose_name='Latitud de Destino')),
                ('lng_destination', models.CharField(max_length=50, verbose_name='Longitud de Destino')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('score', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('date', models.DateField(default=datetime.datetime(2018, 6, 20, 17, 52, 47, 468685), verbose_name='Fecha de Evento')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Ruta turistica',
                'verbose_name_plural': 'Rutas turisticas',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='TourismRouteDestiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Destino de Ruta Turistica',
                'verbose_name_plural': 'Destinos de Rutas Turisticas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TourismRouteMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.CharField(default='NA', max_length=350, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismRoute', verbose_name='Ruta Turistica')),
            ],
            options={
                'verbose_name': 'Menu de Ruta Turistica',
                'verbose_name_plural': 'Menu  de Rutas Turisticas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TourismSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitud')),
                ('lng', models.CharField(max_length=50, verbose_name='Longitud')),
                ('score', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('address', models.CharField(default='sn', max_length=150, verbose_name='Direccion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
            ],
            options={
                'verbose_name': 'Sitio turistico',
                'verbose_name_plural': 'Sitios turisticos',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='TourismSiteDestiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Destino de Sitio Turistico',
                'verbose_name_plural': 'Destinos de Sitios Turisticos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TourismSiteMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.CharField(default='NA', max_length=150, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismSite', verbose_name='Sitio Turistico')),
            ],
            options={
                'verbose_name': 'Menu de Sitio Turistico',
                'verbose_name_plural': 'Menu  de Sitios Turisticos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TourismSiteSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, verbose_name='Dia')),
                ('schedule', models.CharField(default='NA', max_length=50, verbose_name='Horario')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismSite', verbose_name='Sitio Turistico')),
            ],
            options={
                'verbose_name': 'Horario de Atencion de Sitio Turistico',
                'verbose_name_plural': 'Horarios de Atencion de Sitios Turisticos',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='TourismSiteService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Item de servicio')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Servicio de Sitio Turistico',
                'verbose_name_plural': 'Servicios  de Sitios Turisticos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TourismSiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Tipo de Sitio Turistico',
                'verbose_name_plural': 'Tipos de Sitios Turisticos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('address', models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitud')),
                ('lng', models.CharField(max_length=50, verbose_name='Longitud')),
                ('score', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='TransportDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('schedules_out', models.CharField(default='NA', max_length=150, verbose_name='Horarios de salida')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Transport', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Destino de Transporte',
                'verbose_name_plural': 'Destinos de Transportes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TransportSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, verbose_name='Dia')),
                ('schedule', models.CharField(default='NA', max_length=50, verbose_name='Horario')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Transport', verbose_name='Transporte')),
            ],
            options={
                'verbose_name': 'Horario de Atencion de Transporte',
                'verbose_name_plural': 'Horarios de Atencion de Transportes',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Item de servicio')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
            ],
            options={
                'verbose_name': 'Servicio de Transporte',
                'verbose_name_plural': 'Servicios  de Transportes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TransportTypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Tipo de Servicio')),
                ('price', models.DecimalField(decimal_places=2, default=5.1, max_digits=5, verbose_name='Precio')),
                ('image_bus', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen de Bus')),
                ('image_seat', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen de Butacas')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='F. Actualizacion')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TransportDestination', verbose_name='Destino')),
                ('service', models.ManyToManyField(to='tour.TransportService', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio de Transporte',
                'verbose_name_plural': 'Tipos de Servicios de Transportes',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='tourismsite',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismSiteDestiny', verbose_name='Localizacion'),
        ),
        migrations.AddField(
            model_name='tourismsite',
            name='service',
            field=models.ManyToManyField(to='tour.TourismSiteService', verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='tourismsite',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismSiteType', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='tourismroute',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismRouteDestiny', verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service',
            field=models.ManyToManyField(to='tour.RestaurantService', verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='service',
            field=models.ManyToManyField(to='tour.LodgingService', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.LodgingType', verbose_name='Tipo'),
        ),
    ]
