# Generated by Django 2.0.3 on 2018-04-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourim_site',
            new_name='Tourism_site',
        ),
    ]
