# Generated by Django 2.0.4 on 2018-07-11 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingroom',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.1, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 11, 19, 11, 48, 955315), verbose_name='Fecha de Evento'),
        ),
        migrations.AlterField(
            model_name='tourismroutemenu',
            name='description',
            field=models.TextField(default='NA', max_length=350, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tourismsitemenu',
            name='description',
            field=models.TextField(default='NA', max_length=150, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='transporttypeservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.1, max_digits=10, verbose_name='Precio'),
        ),
    ]
