# Generated by Django 2.0.4 on 2018-07-12 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20180711_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(default=' ', max_length=150, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='web',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='duration',
            field=models.CharField(blank=True, default='S/N', max_length=150, verbose_name='Duracion'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='schedule',
            field=models.CharField(blank=True, default='S/N', max_length=150, verbose_name='Horas de Expedicion'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, unique=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='service',
            field=models.ManyToManyField(null=True, to='tour.LodgingService', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='web',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='lodgingroom',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='service',
            field=models.ManyToManyField(null=True, to='tour.RestaurantService', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='web',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 15, 24, 26, 308041), verbose_name='Fecha de Evento'),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='tourismroutemenu',
            name='description',
            field=models.TextField(blank=True, default='NA', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='address',
            field=models.CharField(default=' ', max_length=150, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='service',
            field=models.ManyToManyField(null=True, to='tour.TourismSiteService', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='web',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='tourismsitemenu',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tourismsiteservice',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='web',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='transportdestination',
            name='schedules_out',
            field=models.CharField(blank=True, default='NA', max_length=150, verbose_name='Horarios de salida'),
        ),
        migrations.AlterField(
            model_name='transporttypeservice',
            name='service',
            field=models.ManyToManyField(null=True, to='tour.TransportService', verbose_name='Servicios'),
        ),
    ]
