# Generated by Django 2.0.4 on 2018-05-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20180507_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('address', models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion')),
                ('location', models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion')),
                ('rating', models.DecimalField(decimal_places=1, default=5.1, max_digits=2, verbose_name='Calificacion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('web', models.CharField(default='nn', max_length=150, verbose_name='Pagina Web')),
                ('schedule', models.ManyToManyField(to='tour.Schedule', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Hospedaje',
                'verbose_name_plural': 'Hospedajes',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='LodgingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=5.1, max_digits=5, verbose_name='Precio')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Lodging', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Cuarto de Hospedaje',
                'verbose_name_plural': 'Cuartos de Hospedajes',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='LodgingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(null='true', upload_to='media/', verbose_name='Imagen')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Servicio de Hospedaje',
                'verbose_name_plural': 'Servicios de Hospedajes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LodgingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Tipo de Hospedaje',
                'verbose_name_plural': 'Tipos de Hospedajes',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='lodgment',
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lodgmentroom',
            name='lodgment',
        ),
        migrations.DeleteModel(
            name='Lodgment',
        ),
        migrations.DeleteModel(
            name='LodgmentRoom',
        ),
        migrations.DeleteModel(
            name='LodgmentService',
        ),
        migrations.DeleteModel(
            name='LodgmentType',
        ),
        migrations.AddField(
            model_name='lodging',
            name='service',
            field=models.ManyToManyField(to='tour.LodgingService', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.LodgingType', verbose_name='Tipo'),
        ),
    ]
