# Generated by Django 2.0.4 on 2018-04-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20180413_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lodgmet_type',
            new_name='Lodgment_type',
        ),
    ]
