# Generated by Django 2.0.4 on 2018-05-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20180507_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismsite',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.TourismSiteType', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
