# Generated by Django 2.0.4 on 2018-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20180413_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgment',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='transport',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100),
        ),
    ]
