# Generated by Django 2.0.4 on 2018-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20180712_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='tour.LodgingService', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='tour.RestaurantService', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='tour.TourismSiteService', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='transporttypeservice',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='tour.TransportService', verbose_name='Servicios'),
        ),
    ]
