# Generated by Django 2.0.4 on 2018-05-08 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tourismsite_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='TourismSiteMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismSite', verbose_name='Sitio')),
            ],
        ),
        migrations.DeleteModel(
            name='Objetive',
        ),
        migrations.AlterField(
            model_name='tourismsitetype',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismSiteDestiny', verbose_name='Tipo'),
        ),
    ]
