# Generated by Django 2.0.4 on 2018-04-13 23:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20180413_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism_agency',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='tourism_site',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='transport',
            name='destination',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'SUCRE'), (2, 'LA PAZ'), (3, 'ORURO'), (4, 'SANTA CRUZ'), (5, 'TARIJA'), (6, 'COCHABAMBA'), (7, 'BENI'), (8, 'PANDO')], default=1, max_length=3),
        ),
    ]
