# Generated by Django 2.0.4 on 2018-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20180508_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyservice',
            options={'ordering': ['title'], 'verbose_name': 'Paquete de Agencia', 'verbose_name_plural': 'Paquetes de Agencias'},
        ),
        migrations.AlterModelOptions(
            name='tourismsitemenu',
            options={'ordering': ['title'], 'verbose_name': 'Menu de Sitio Turistico', 'verbose_name_plural': 'Menu  de Sitios Turisticos'},
        ),
        migrations.RemoveField(
            model_name='agencyservice',
            name='image',
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='departures',
            field=models.CharField(default='S/N', max_length=150, verbose_name='Salidas'),
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='duration',
            field=models.CharField(default='S/N', max_length=150, verbose_name='Duracion'),
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='place_start',
            field=models.CharField(default='S/N', max_length=150, verbose_name='Lugar de Inicio'),
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='places_to_known',
            field=models.CharField(default='S/N', max_length=500, verbose_name='Lugares a conocer'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(default='S/N', max_length=150, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='location',
            field=models.URLField(default='', max_length=500, verbose_name='Ubicacion'),
        ),
        migrations.RemoveField(
            model_name='agency',
            name='schedule',
        ),
        migrations.AddField(
            model_name='agency',
            name='schedule',
            field=models.ManyToManyField(to='tour.Schedule', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='service',
            field=models.ManyToManyField(to='tour.AgencyService', verbose_name='Paquetes de turismo'),
        ),
    ]
