# Generated by Django 2.0.4 on 2018-07-23 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0006_auto_20180716_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=12, unique=True, verbose_name='CI')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('gender', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=2, verbose_name='Género')),
                ('rol', models.CharField(choices=[('AD', 'ADMINISTRADOR'), ('US', 'USUARIO')], default='R', max_length=2, verbose_name='Rol')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agency',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='agencyschedule',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='function',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='law',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='lodgingroom',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='lodgingschedule',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='lodgingservice',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='lodgingtype',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='restaurantschedule',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='restaurantservice',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismroutedestiny',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismroutemenu',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismsitedestiny',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismsitemenu',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismsiteschedule',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismsiteservice',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='tourismsitetype',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transport',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='transportdestination',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='transportschedule',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='transportservice',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='transporttypeservice',
            name='register_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
    ]
