# Generated by Django 2.0.4 on 2018-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20180508_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='transportservice',
            name='image',
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='schedule',
            field=models.CharField(default='S/N', max_length=150, verbose_name='Horas de Expedicion'),
        ),
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.FileField(null='true', upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='image',
            field=models.ImageField(null='true', upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='transportdestination',
            name='schedules_out',
            field=models.CharField(default='NA', max_length=150, verbose_name='Horarios de salida'),
        ),
        migrations.AddField(
            model_name='transportservice',
            name='image_bus',
            field=models.ImageField(null='true', upload_to='media/', verbose_name='Imagen de Bus'),
        ),
        migrations.AddField(
            model_name='transportservice',
            name='image_seat',
            field=models.ImageField(null='true', upload_to='media/', verbose_name='Imagen de Butacas'),
        ),
        migrations.AlterField(
            model_name='tourismsitemenu',
            name='description',
            field=models.CharField(default='NA', max_length=150, verbose_name='Descripcion'),
        ),
    ]
