# Generated by Django 2.0.4 on 2018-04-13 23:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20180413_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='destination',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'SUCRE'), (2, 'LA PAZ'), (3, 'ORURO'), (4, 'SANTA CRUZ'), (5, 'TARIJA'), (6, 'COCHABAMBA'), (7, 'BENI'), (8, 'PANDO')], default=1, max_length=10),
        ),
    ]
