# Generated by Django 2.0.4 on 2018-05-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20180511_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportservice',
            name='image_bus',
        ),
        migrations.RemoveField(
            model_name='transportservice',
            name='image_seat',
        ),
        migrations.AddField(
            model_name='transportservice',
            name='image',
            field=models.ImageField(null='true', upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='transporttypeservice',
            name='image_bus',
            field=models.ImageField(null='true', upload_to='media/', verbose_name='Imagen de Bus'),
        ),
        migrations.AddField(
            model_name='transporttypeservice',
            name='image_seat',
            field=models.ImageField(null='true', upload_to='media/', verbose_name='Imagen de Butacas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='file',
            field=models.FileField(null='true', upload_to='media/', verbose_name='Imagen o Video'),
        ),
    ]
