# Generated by Django 2.0.4 on 2018-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20180723_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='category',
            field=models.CharField(choices=[('EN', 'ENTRADAS'), ('PO', 'POSTRES'), ('DE', 'DESAYUNO'), ('SE', 'SEGUNDOS'), ('BE', 'BEBIDAS'), ('CV', 'CARTA DE VINOS'), ('SO', 'SOPAS')], default='1', max_length=2, verbose_name='Categoria'),
        ),
    ]
