# Generated by Django 2.0.4 on 2018-07-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_restaurantmenu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyservice',
            name='departures',
            field=models.CharField(default=' ', max_length=350, verbose_name='Dias de expedicion'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='duration',
            field=models.IntegerField(blank=True, default=1, verbose_name='Duracion'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='place_start',
            field=models.CharField(default=' ', max_length=350, verbose_name='Lugar de Partida'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='places_to_known',
            field=models.TextField(default='S/N', verbose_name='Lugares a conocer'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='schedule',
            field=models.CharField(blank=True, default='8:00', max_length=350, verbose_name='Horas de partida'),
        ),
    ]
