# Generated by Django 2.0.4 on 2018-07-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_auto_20180725_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyservice',
            name='image',
            field=models.ImageField(null='true', upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='places_to_known',
            field=models.TextField(default=' ', verbose_name='Lugares a conocer'),
        ),
    ]
