# Generated by Django 2.0.4 on 2018-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_auto_20180414_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_agency',
            name='title',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AddField(
            model_name='service_lodgment',
            name='title',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AddField(
            model_name='service_restaurant',
            name='title',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AddField(
            model_name='service_transport',
            name='title',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AlterField(
            model_name='lodgment_type',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='service_agency',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service_lodgment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service_restaurant',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service_transport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
