# Generated by Django 2.0.4 on 2018-07-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_auto_20180725_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyservice',
            name='place_start',
            field=models.CharField(default=' ', max_length=350, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='places_to_known',
            field=models.TextField(default=' ', verbose_name='Descripcion'),
        ),
    ]
