# Generated by Django 2.0.4 on 2018-04-20 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_auto_20180414_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodgment',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='tourism_site',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='transport',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='location',
            field=models.URLField(verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.URLField(verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='address',
            field=models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='location',
            field=models.URLField(verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Lodgment_type', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lodgment_type',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='lodgment_type',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.URLField(verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='service_agency',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='service_agency',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='service_lodgment',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='service_lodgment',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='service_restaurant',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='service_restaurant',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='service_transport',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='service_transport',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='tourism_site',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tourism_site',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tourism_site',
            name='location',
            field=models.URLField(verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='tourism_site',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='tourism_site',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='tourism_site',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='address',
            field=models.CharField(default='S/N', max_length=150, unique=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='destination',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'SUCRE'), (2, 'LA PAZ'), (3, 'ORURO'), (4, 'SANTA CRUZ'), (5, 'TARIJA'), (6, 'COCHABAMBA'), (7, 'BENI'), (8, 'PANDO')], default=1, max_length=100, verbose_name='Destinos'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='location',
            field=models.URLField(verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='rating',
            field=models.CharField(choices=[('1', '✭'), ('2', '✭✭'), ('3', '✭✭✭'), ('4', '✭✭✭✭'), ('5', '✭✭✭✭✭')], default=1, max_length=100, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
    ]
