# Generated by Django 2.0.4 on 2018-07-31 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_auto_20180727_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nombre')),
                ('register_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['title'],
                'permissions': (('show_location', 'Can Details Location'), ('index_location', 'Can List Location')),
            },
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['score'], 'permissions': (('show_agency', 'Can Details Agency'), ('index_agency', 'Can List Agency')), 'verbose_name': 'Agencia de turismo', 'verbose_name_plural': 'Agencias de turismo'},
        ),
        migrations.AlterModelOptions(
            name='agencyschedule',
            options={'ordering': ['register_at'], 'permissions': (('show_agencyschedule', 'Can Details Schedule Agency'), ('index_agencyschedule', 'Can List Schedule Agency')), 'verbose_name': 'Horario de Atencion', 'verbose_name_plural': 'Horarios de Atencion'},
        ),
        migrations.AlterModelOptions(
            name='agencyservice',
            options={'ordering': ['title'], 'permissions': (('show_agencyservice', 'Can Details Service Agency'), ('index_agencyservice', 'Can List Service Agency')), 'verbose_name': 'Paquete de Agencia', 'verbose_name_plural': 'Paquetes de Agencias'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('show_client', 'Can Details Client'), ('index_client', 'Can List Client')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date'], 'permissions': (('show_event', 'Can Details Event'), ('index_event', 'Can List Event')), 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['description'], 'permissions': (('show_fucntion', 'Can Details Function'), ('index_function', 'Can List Function')), 'verbose_name': 'Funcion', 'verbose_name_plural': 'Funciones'},
        ),
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['title'], 'permissions': (('show_law', 'Can Details Law'), ('index_law', 'Can List Law')), 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='lodging',
            options={'ordering': ['score'], 'permissions': (('show_lodging', 'Can Details Lodging'), ('index_lodging', 'Can List Lodging')), 'verbose_name': 'Hospedaje', 'verbose_name_plural': 'Hospedajes'},
        ),
        migrations.AlterModelOptions(
            name='lodgingroom',
            options={'ordering': ['price'], 'permissions': (('show_lodgingroom', 'Can Details Room Lodging'), ('index_lodgingroom', 'Can List Room Lodging')), 'verbose_name': 'Cuarto de Hospedaje', 'verbose_name_plural': 'Cuartos de Hospedajes'},
        ),
        migrations.AlterModelOptions(
            name='lodgingschedule',
            options={'ordering': ['register_at'], 'permissions': (('show_lodgingschedule', 'Can Details Schedule Lodging'), ('index_lodgingschedule', 'Can List Schedule Lodging')), 'verbose_name': 'Horario de Atencion de Hospedaje', 'verbose_name_plural': 'Horarios de Atencion de Hospedajes'},
        ),
        migrations.AlterModelOptions(
            name='lodgingservice',
            options={'ordering': ['title'], 'permissions': (('show_lodgingservice', 'Can Details Service Lodging'), ('index_lodgingservice', 'Can List Service Lodging')), 'verbose_name': 'Servicio de Hospedaje', 'verbose_name_plural': 'Servicios de Hospedajes'},
        ),
        migrations.AlterModelOptions(
            name='lodgingtype',
            options={'ordering': ['title'], 'permissions': (('show_lodgingtype', 'Can Details Type Lodging'), ('index_lodgingtype', 'Can List Type Lodging')), 'verbose_name': 'Tipo de Hospedaje', 'verbose_name_plural': 'Tipos de Hospedajes'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['description'], 'permissions': (('show_objective', 'Can Details Objective'), ('index_objective', 'Can List Objective')), 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['score'], 'permissions': (('show_restaurant', 'Can Details Restaurant'), ('index_restaurant', 'Can List Restaurant')), 'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='restaurantmenu',
            options={'ordering': ['price'], 'permissions': (('show_restaurantmeu', 'Can Details Menu Restaurant'), ('index_restaurantmenu', 'Can List Menu Restaurant')), 'verbose_name': 'Menu de Restaurante', 'verbose_name_plural': 'Menus de Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='restaurantschedule',
            options={'ordering': ['register_at'], 'permissions': (('show_restaurantschedule', 'Can Details Schedule Restaurant'), ('index_restaurantschedule', 'Can List Schedule Restaurant')), 'verbose_name': 'Horario de Atencion de Restaurant', 'verbose_name_plural': 'Horarios de Atencion de Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='restaurantservice',
            options={'ordering': ['title'], 'permissions': (('show_restaurantservice', 'Can Details Service Restaurant'), ('index_restaurantservice', 'Can List Service Restaurant')), 'verbose_name': 'Servicio de Restaurante', 'verbose_name_plural': 'Servicios de Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='tourismroute',
            options={'ordering': ['score'], 'permissions': (('show_tourismroute', 'Can Details Service Tourism Route'), ('index_tourismroute', 'Can List Service Tourism Route')), 'verbose_name': 'Ruta turistica', 'verbose_name_plural': 'Rutas turisticas'},
        ),
        migrations.AlterModelOptions(
            name='tourismroutemenu',
            options={'ordering': ['title'], 'permissions': (('show_tourismroutemenu', 'Can Details Tourism Route Menu'), ('index_tourismroutemenu', 'Can List Tourism Route Menu')), 'verbose_name': 'Menu de Ruta Turistica', 'verbose_name_plural': 'Menu  de Rutas Turisticas'},
        ),
        migrations.AlterModelOptions(
            name='tourismsite',
            options={'ordering': ['score'], 'permissions': (('show_tourismsite', 'Can Details Tourism Site'), ('index_tourismsite', 'Can List Tourism Site')), 'verbose_name': 'Sitio turistico', 'verbose_name_plural': 'Sitios turisticos'},
        ),
        migrations.AlterModelOptions(
            name='tourismsitemenu',
            options={'ordering': ['title'], 'permissions': (('show_tourismsitemenu', 'Can Details Menu Tourism Site'), ('index_tourismsitemenu', 'Can List Menu Tourism Site')), 'verbose_name': 'Menu de Sitio Turistico', 'verbose_name_plural': 'Menu  de Sitios Turisticos'},
        ),
        migrations.AlterModelOptions(
            name='tourismsiteschedule',
            options={'ordering': ['register_at'], 'permissions': (('show_tourismsiteschedule', 'Can Details Schedule Tourism Site'), ('index_tourismsiteschedule', 'Can List Schedule Tourism Site')), 'verbose_name': 'Horario de Atencion de Sitio Turistico', 'verbose_name_plural': 'Horarios de Atencion de Sitios Turisticos'},
        ),
        migrations.AlterModelOptions(
            name='tourismsiteservice',
            options={'ordering': ['title'], 'permissions': (('show_tourismsiteservice', 'Can Details Service Tourism Site'), ('index_tourismsiteservice', 'Can List Service Tourism Site')), 'verbose_name': 'Servicio de Sitio Turistico', 'verbose_name_plural': 'Servicios  de Sitios Turisticos'},
        ),
        migrations.AlterModelOptions(
            name='tourismsitetype',
            options={'ordering': ['title'], 'permissions': (('show_tourismsitetype', 'Can Details Type Tourism Site'), ('index_tourismsitetype', 'Can List Type Tourism Site')), 'verbose_name': 'Tipo de Sitio Turistico', 'verbose_name_plural': 'Tipos de Sitios Turisticos'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['score'], 'permissions': (('show_transport', 'Can Details Transport'), ('index_transport', 'Can List Transport')), 'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
        migrations.AlterModelOptions(
            name='transportdestination',
            options={'ordering': ['title'], 'permissions': (('show_transportdestination', 'Can Details Destination Transport'), ('index_transportdestination', 'Can List Destination Transport')), 'verbose_name': 'Destino de Transporte', 'verbose_name_plural': 'Destinos de Transportes'},
        ),
        migrations.AlterModelOptions(
            name='transportschedule',
            options={'ordering': ['register_at'], 'permissions': (('show_transportschedule', 'Can Details Schedule Transport'), ('index_transportschedule', 'Can List Schedule Transport')), 'verbose_name': 'Horario de Atencion de Transporte', 'verbose_name_plural': 'Horarios de Atencion de Transportes'},
        ),
        migrations.AlterModelOptions(
            name='transportservice',
            options={'ordering': ['title'], 'permissions': (('show_transportservice', 'Can Details Service Transport'), ('index_transportservice', 'Can List Service Transport')), 'verbose_name': 'Servicio de Transporte', 'verbose_name_plural': 'Servicios  de Transportes'},
        ),
        migrations.AlterModelOptions(
            name='transporttypeservice',
            options={'ordering': ['title'], 'permissions': (('show_transporttypeservice', 'Can Details Type Service Transport'), ('index_transporttypeservice', 'Can List Type Service Transport')), 'verbose_name': 'Tipo de Servicio de Transporte', 'verbose_name_plural': 'Tipos de Servicios de Transportes'},
        ),
        migrations.AlterField(
            model_name='agency',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='agencyschedule',
            name='day',
            field=models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, unique=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='lodgingroom',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='lodgingschedule',
            name='day',
            field=models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, unique=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='lodgingservice',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='lodgingtype',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='restaurantschedule',
            name='day',
            field=models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, unique=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='restaurantservice',
            name='title',
            field=models.TextField(default='NA', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismroutemenu',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismsitemenu',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismsiteschedule',
            name='day',
            field=models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, unique=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='tourismsitetype',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='transportdestination',
            name='title',
            field=models.CharField(default='NA', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='transportschedule',
            name='day',
            field=models.CharField(choices=[('LU', 'LUNES'), ('MA', 'MARTES'), ('MI', 'MIERCOLES'), ('JU', 'JUEVES'), ('VI', 'VIERNES'), ('SA', 'SABADO'), ('DO', 'DOMINGO')], default='1', max_length=2, unique=True, verbose_name='Dia'),
        ),
        migrations.DeleteModel(
            name='TourismRouteDestiny',
        ),
        migrations.DeleteModel(
            name='TourismSiteDestiny',
        ),
        migrations.AddField(
            model_name='agency',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
        ),
        migrations.AddField(
            model_name='event',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
        ),
        migrations.AddField(
            model_name='transport',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
        ),
    ]
