# Generated by Django 2.0.4 on 2018-04-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_auto_20180420_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tourism_site',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='rating',
        ),
    ]
