# Generated by Django 2.0.4 on 2018-08-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_auto_20180731_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lodging',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.Location', verbose_name='Localizacion'),
            preserve_default=False,
        ),
    ]
