# Generated by Django 2.0.4 on 2018-08-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_auto_20180801_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('rol', models.CharField(choices=[('AD', 'ADMINISTRADOR'), ('US', 'USUARIO')], default='R', max_length=2, verbose_name='Rol')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Secretario',
                'verbose_name_plural': 'Secretario',
                'permissions': (('show_secretary', 'Can Details Secretary'), ('index_secretary', 'Can List Secretary')),
            },
        ),
        migrations.RemoveField(
            model_name='law',
            name='description',
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.TextField(blank=True, unique=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='service',
            field=models.ManyToManyField(blank=True, to='tour.LodgingService', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='service',
            field=models.ManyToManyField(blank=True, to='tour.RestaurantService', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='service',
            field=models.ManyToManyField(blank=True, to='tour.TourismSiteService', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='transporttypeservice',
            name='service',
            field=models.ManyToManyField(blank=True, to='tour.TransportService', verbose_name='Servicios'),
        ),
    ]
