# Generated by Django 2.0.4 on 2018-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_auto_20180425_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
        ),
    ]
