# Generated by Django 2.0.4 on 2018-04-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_funciones_objetivos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objetivos',
            new_name='Function',
        ),
        migrations.RenameModel(
            old_name='Funciones',
            new_name='Objetive',
        ),
    ]
