# Generated by Django 2.0.4 on 2018-08-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_auto_20180802_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Imagen'),
        ),
    ]
