# Generated by Django 2.0.4 on 2018-08-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_auto_20180813_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(max_length=350, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.CharField(max_length=350, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(max_length=350, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='social',
            name='whatsapp',
            field=models.CharField(max_length=350, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.CharField(max_length=350, verbose_name='Youtube'),
        ),
    ]
