# Generated by Django 2.0.4 on 2018-04-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_auto_20180426_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='schedule',
            field=models.CharField(default='--', max_length=150, verbose_name='Horarios'),
        ),
        migrations.AddField(
            model_name='agency',
            name='web',
            field=models.CharField(default='nn', max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.CharField(default='--', max_length=150, verbose_name='Horarios'),
        ),
        migrations.AddField(
            model_name='event',
            name='web',
            field=models.CharField(default='nn', max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AddField(
            model_name='lodgment',
            name='schedule',
            field=models.CharField(default='--', max_length=150, verbose_name='Horarios'),
        ),
        migrations.AddField(
            model_name='lodgment',
            name='web',
            field=models.CharField(default='nn', max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='schedule',
            field=models.CharField(default='--', max_length=150, verbose_name='Horarios'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='web',
            field=models.CharField(default='nn', max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AddField(
            model_name='transport',
            name='schedule',
            field=models.CharField(default='--', max_length=150, verbose_name='Horarios'),
        ),
        migrations.AddField(
            model_name='transport',
            name='web',
            field=models.CharField(default='nn', max_length=150, verbose_name='Pagina Web'),
        ),
    ]
