# Generated by Django 2.0.4 on 2018-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_auto_20180427_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=150, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
        ),
    ]
