# Generated by Django 2.0.4 on 2018-04-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_menu_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_restaurant',
            name='description',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(to='tour.Menu_Restaurant'),
        ),
    ]
