# Generated by Django 2.0.4 on 2018-08-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_auto_20180813_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rol',
            field=models.CharField(choices=[('AD', 'ADMINISTRADOR'), ('US-L', 'USUARIO-HOSPEDAJE'), ('US-T', 'USUARIO-TRANSPORTE'), ('US-R', 'USUARIO-RESTAURANT'), ('US-AT', 'USUARIO-AGENCIA-TURISTICA'), ('US-ST', 'USUARIO-SITIO-TURISTICO')], default='R', max_length=2, verbose_name='Rol'),
        ),
    ]
