# Generated by Django 2.0.4 on 2018-08-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_auto_20180813_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyschedule',
            options={'ordering': ['register_at'], 'permissions': (('show_agencyschedule', 'Can Details Schedule Agency'), ('index_agencyschedule', 'Can List Schedule Agency')), 'verbose_name': 'Horario de Atencion de Agencia', 'verbose_name_plural': 'Horarios de Atencion de Agencias'},
        ),
        migrations.AlterField(
            model_name='client',
            name='rol',
            field=models.CharField(choices=[('AD', 'ADMINISTRADOR'), ('US-L', 'USUARIO-HOSPEDAJE'), ('US-T', 'USUARIO-TRANSPORTE'), ('US-R', 'USUARIO-RESTAURANT'), ('US-AT', 'USUARIO-AGENCIA-TURISTICA'), ('US-ST', 'USUARIO-SITIO-TURISTICO')], default='R', max_length=10, verbose_name='Rol'),
        ),
    ]
