# Generated by Django 2.0.4 on 2018-04-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_auto_20180430_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='NA', max_length=150, verbose_name='Dia')),
                ('description', models.CharField(default='NA', max_length=150, verbose_name='Descripcion')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='lodgment_type',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='menu_restaurant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.1, max_digits=5, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='menu_restaurant',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='service_agency',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='service_lodgment',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='service_restaurant',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AddField(
            model_name='service_transport',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name='Fecha de Evento'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(to='tour.Menu_Restaurant', verbose_name='Menu'),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='service',
            field=models.ManyToManyField(to='tour.Service_Restaurant', verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='schedule',
            field=models.ManyToManyField(to='tour.Schedule_Restaurant', verbose_name='Horario'),
        ),
    ]
