# Generated by Django 2.0.4 on 2018-04-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_auto_20180430_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='location',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion'),
        ),
    ]
