# Generated by Django 2.0.4 on 2018-04-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0023_auto_20180430_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='location',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='tourism_site',
            name='location',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='location',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ubicacion'),
        ),
    ]
