# Generated by Django 2.0.4 on 2018-08-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0023_auto_20180817_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='is_active',
        ),
    ]
