# Generated by Django 2.0.4 on 2018-09-01 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0024_auto_20180817_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Agency', verbose_name='Agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Client', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentLodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Client', verbose_name='Cliente')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Lodging', verbose_name='Hospedaje')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Client', verbose_name='Cliente')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Restaurant', verbose_name='Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Client', verbose_name='Cliente')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourismSite', verbose_name='Sitio Turistico')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Client', verbose_name='Cliente')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Transport', verbose_name='Transporte')),
            ],
        ),
    ]
