# Generated by Django 2.0.3 on 2018-09-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0026_auto_20180905_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.ImageField(upload_to='media/agencies/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='agencyservice',
            name='image',
            field=models.ImageField(null='true', upload_to='media/agencies/services/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='file',
            field=models.FileField(null='true', upload_to='media/events/', verbose_name='Imagen o Video'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='image',
            field=models.ImageField(upload_to='media/lodgings/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='lodgingroom',
            name='image',
            field=models.ImageField(upload_to='media/lodgings/rooms/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='lodgingservice',
            name='image',
            field=models.ImageField(null='true', upload_to='media/lodgings/services/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='media/restaurants/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='image',
            field=models.ImageField(null='true', upload_to='media/restaurants/menus/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='restaurantservice',
            name='image',
            field=models.ImageField(null='true', upload_to='media/restaurants/services/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='image',
            field=models.ImageField(null=True, upload_to='media/secretaries/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tourismroute',
            name='image',
            field=models.ImageField(upload_to='media/t-routes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tourismroutemenu',
            name='image',
            field=models.ImageField(upload_to='media/t-routes/menus/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tourismsite',
            name='image',
            field=models.ImageField(upload_to='media/t-sites/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tourismsitemenu',
            name='image',
            field=models.ImageField(upload_to='media/t-sites/menus/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tourismsiteservice',
            name='image',
            field=models.ImageField(upload_to='media/t-sites/services/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='image',
            field=models.ImageField(upload_to='media/transports/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='transportservice',
            name='image',
            field=models.ImageField(null='true', upload_to='media/transports/services/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='transporttypeservice',
            name='image_bus',
            field=models.ImageField(null='true', upload_to='media/transports/buses/', verbose_name='Imagen de Bus'),
        ),
        migrations.AlterField(
            model_name='transporttypeservice',
            name='image_seat',
            field=models.ImageField(null='true', upload_to='media/transports/seats/', verbose_name='Imagen de Butacas'),
        ),
    ]
