# Generated by Django 2.0.3 on 2018-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0027_auto_20180912_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentagency',
            options={'ordering': ['client', 'agency'], 'permissions': (('show_assignment_agency', 'Can Details AssignmentAgency'), ('index_assignment_agency', 'Can List AssignmentAgency')), 'verbose_name': 'Asignacion de Agencia Turistica', 'verbose_name_plural': 'Asignaciones de Agencias Turisticas'},
        ),
        migrations.AlterModelOptions(
            name='assignmentlodging',
            options={'ordering': ['client', 'lodging'], 'permissions': (('show_assignment_lodging', 'Can Details AssignmentLodging'), ('index_assignment_lodging', 'Can List AssignmentLodging')), 'verbose_name': 'Asignacion de Hospedaje', 'verbose_name_plural': 'Asignaciones de Hospedajes'},
        ),
        migrations.AlterModelOptions(
            name='assignmentrestaurant',
            options={'ordering': ['client', 'restaurant'], 'permissions': (('show_assignment_restaurant', 'Can Details AssignmentRestaurant'), ('index_assignment_restaurant', 'Can List AssignmentRestaurant')), 'verbose_name': 'Asignacion de Restaurant', 'verbose_name_plural': 'Asignaciones de Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='assignmentsite',
            options={'ordering': ['client', 'site'], 'permissions': (('show_assignment_site', 'Can Details AssignmentSite'), ('index_assignment_site', 'Can List AssignmentSite')), 'verbose_name': 'Asignacion de Sitio Turistico', 'verbose_name_plural': 'Asignaciones de Sitios Turisticos'},
        ),
        migrations.AlterModelOptions(
            name='assignmenttransport',
            options={'ordering': ['client', 'transport'], 'permissions': (('show_assignment_transport', 'Can Details AssignmentTransport'), ('index_assignment_transport', 'Can List AssignmentTransport')), 'verbose_name': 'Asignacion de Transporte', 'verbose_name_plural': 'Asignaciones de Transportes'},
        ),
        migrations.AddField(
            model_name='assignmentagency',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='assignmentlodging',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='assignmentrestaurant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='assignmentsite',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='assignmenttransport',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
